import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("data/processed_student_performance.csv")

plt.figure(figsize=(10, 5))
plt.bar(df["Student"], df["Final_Score"], color="royalblue")
plt.title("Student Names vs Final Scores")
plt.xlabel("Student Name")
plt.ylabel("Final Score")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("plots/final_scores.png")
plt.close()

plt.figure(figsize=(8, 5))
plt.scatter(df["Hours_Studied"], df["Final_Score"], color="crimson", edgecolor="black")
plt.title("Hours Studied vs Final Score")
plt.xlabel("Hours Studied")
plt.ylabel("Final Score")
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.savefig("plots/study_vs_score.png")
plt.close()

plt.figure(figsize=(8, 5))
plt.hist(df["Final_Score"], bins=10, color="forestgreen", edgecolor="black")
plt.title("Distribution of Final Scores")
plt.xlabel("Final Score")
plt.ylabel("Number of Students")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.savefig("plots/score_distribution.png")
plt.close()

plt.figure(figsize=(8, 5))
plt.scatter(df["Attendance"], df["Improvement"], color="purple", edgecolor="black")
plt.axhline(0, color="gray", linestyle="--", linewidth=1)
plt.title("Attendance vs Score Improvement")
plt.xlabel("Attendance (%)")
plt.ylabel("Score Improvement")
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.savefig("plots/custom_plot.png")
plt.close()